export const SET_COUNTRY_LIST = 'COUNTRY/SET_COUNTRY_LIST';
export const SET_ARE_MORE_COUNTRIES_LEFT_TO_SHOW = 'COUNTRY/SET_ARE_MORE_COUNTRIES_LEFT_TO_SHOW';
export const SET_IS_MOCK_COUNTRY_LIST_POPULATED = 'COUNTRY/SET_IS_MOCK_COUNTRY_LIST_POPULATED';
export const SET_TOTAL_COUNTRY_COUNT = 'COUNTRY/SET_TOTAL_COUNTRY_COUNT';
